### PR TITLE
Don't use minified file because of source mapping issues

### PR DESCRIPTION
**Pull request by joostdevries**
https://github.com/ember-cli/ember-cli-uglify/issues/4#issuecomment-169362253

### CODE REVIEW

**Comment by joostdevries** [comment]
@pixelhandler ping

**Comment by pixelhandler** [comment]
@joostdevries what are the source mapping issues?

**Comment by joostdevries** [comment]
@pixelhandler as mentioned in https://github.com/ember-cli/ember-cli-uglify/issues/4#issuecomment-169362253, ember-cli-uglify breaks when there are sourcemap refs present in the source files.

**Comment by pixelhandler** [comment]
thanks @joostdevries, I merged, tagged 0.2.0, and npm published :)

**Comment by joostdevries** [comment]
awesome, thanks!

**Pull request merged**
